#ifndef ERR_H
#define ERR_H

typedef enum {
  DS_SUCCESS,
  DS_ERR_VECTOR_OUT_OF_BOUNDS_READ,
  DS_ERR_VECTOR_DOES_NOT_EXIST,
  DS_ERR_VECTOR_OUT_OF_BOUNDS_WRITE,
  DS_ERR_VECTOR_VAL_SIZE_INCOMPATIBLE,
  DS_ERR_VECTOR_CAP_LESS_THAN_SIZE,
  DS_ERR_VECTOR_DATA_TYPE_NON_NUMERICAL,
  DS_ERR_MALLOC_FAULT,
} StatusCode;

#endif
